name: json_to_floor_entity
description: Generate Floor (a flutter plugin provides a neat SQLite abstraction like Room) entities class and DAO class from Json file.
version: 1.1.2
homepage: https://github.com/zxskigg/flutter_json_to_floor_entity

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  logging: ^1.0.1
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.6




# dart pub publish